export interface CalendarEvent {
  summary: string;
  description: string;
  start: {
    dateTime: string;
    timeZone: string;
  };
  end: {
    dateTime: string;
    timeZone: string;
  };
}

export const exportToGoogleCalendar = async (token: string, event: CalendarEvent) => {
  const response = await fetch("https://www.googleapis.com/calendar/v3/calendars/primary/events", {
    method: "POST",
    headers: {
      Authorization: `Bearer ${token}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify(event),
  });

  if (!response.ok) {
    const error = await response.json();
    throw new Error(error.error.message || "Failed to export to calendar");
  }

  return response.json();
};

export const syncWeekToCalendar = async (token: string, mealPlan: any[], language: string) => {
  const results = [];
  for (const day of mealPlan) {
    if (day.breakfast) {
      results.push(await exportToGoogleCalendar(token, {
        summary: `🍳 BB Breakfast: ${day.breakfast.title[language]}`,
        description: `Recipe: ${day.breakfast.title[language]}\nGenerated by BalkanBite AI`,
        start: { dateTime: `${day.date}T08:00:00Z`, timeZone: "UTC" },
        end: { dateTime: `${day.date}T09:00:00Z`, timeZone: "UTC" }
      }));
    }
    if (day.lunch) {
      results.push(await exportToGoogleCalendar(token, {
        summary: `🥗 BB Lunch: ${day.lunch.title[language]}`,
        description: `Recipe: ${day.lunch.title[language]}\nGenerated by BalkanBite AI`,
        start: { dateTime: `${day.date}T13:00:00Z`, timeZone: "UTC" },
        end: { dateTime: `${day.date}T14:00:00Z`, timeZone: "UTC" }
      }));
    }
    if (day.dinner) {
      results.push(await exportToGoogleCalendar(token, {
        summary: `🍲 BB Dinner: ${day.dinner.title[language]}`,
        description: `Recipe: ${day.dinner.title[language]}\nGenerated by BalkanBite AI`,
        start: { dateTime: `${day.date}T20:00:00Z`, timeZone: "UTC" },
        end: { dateTime: `${day.date}T21:00:00Z`, timeZone: "UTC" }
      }));
    }
  }
  return results;
};
